# Generated by Django 3.2.25 on 2026-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260202_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_user', 'Nouvel Utilisateur'), ('new_admin', 'Nouvel Administrateur'), ('new_session', 'Nouvelle Session'), ('pdf_generated', 'PDF Généré'), ('system', 'Système')], default='system', max_length=20),
        ),
    ]
